### PR TITLE
snapshot -- fully qualified resource names

### PR DESCRIPTION
**Pull request by joekelley**
Done:
- [x] input snapshot
- [x] input reconciler
- [x] hybrid input reconciler
- [x] input snapshot manual builder

TODO:
- [x] output snapshot

BOT NOTES: 
resolves https://github.com/solo-io/skv2/issues/151

### CODE REVIEW

**Comment by joekelley** [comment]
it works! see https://github.com/solo-io/gloo-mesh/pull/1226

**Comment by joekelley** [comment]
@ashleywang1 correct!

**Comment by ashleywang1** [comment]
This is the PR in gloo-fed once skv2 v0.18.0 comes out - it was a lot easier than I was expecting! https://github.com/solo-io/gloo-fed/pull/321

**Review by harveyxia — COMMENTED** [review]
lgtm, @ilackarms did you want to review?

**Pull request closed without merging**
